name: "Sphinx: build && deploy docs"

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Sphinx docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Cache Poetry and pip
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock','**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        run: pip install poetry

      - name: Install project + docs dependencies
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project false
          poetry install --no-interaction --no-ansi --with docs

      - name: Build HTML docs
        run: |
          poetry run sphinx-build -b html docs docs/_build/html
          echo "pyjiit.codelif.in" > docs/_build/html/CNAME

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Set up GitHub Pages
        uses: actions/setup-pages@v4

      - name: Deploy to Pages
        uses: actions/upload-pages-deployment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
